
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-courses-s26-02
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-02
pull_requests: [{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"default-course-schedule","number":50,"title":"Default course schedule","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/50"},{"author":{"id":"U_kgDOCMR-Zg","is_bot":false,"login":"Andrew-UCSB","name":""},"headRefName":"Ab-EndQtr-from-currentQtr-UCSBAPIQuarterService-ScheduledJobs-IsStaleServiceTests","number":47,"title":"Made endQtrYYYQ pull from getCurrentEndQuarter rather than env variable for remaining backend files.","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/47"},{"author":{"id":"MDQ6VXNlcjc5NDc1MDQx","is_bot":false,"login":"Bombboox","name":"Arman Petrosyan"},"headRefName":"arman_course_search","number":46,"title":"Course Description Search Backend Endpoint","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/46"},{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"enrollment-history-page","number":45,"title":" added enrollmentHistory page + tests","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/45"},{"author":{"id":"U_kgDOB3D2TQ","is_bot":false,"login":"just-in-fan","name":"Justin Fan"},"headRefName":"jf-CourseHistorySearchFeedback","number":42,"title":"Course History Search Page: Added Loading Message and No Sections found when no courses","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/42"},{"author":{"id":"U_kgDOB3D2TQ","is_bot":false,"login":"just-in-fan","name":"Justin Fan"},"headRefName":"jf-BasicCourseSearchFeedbackNotLogIn","number":41,"title":"Main Search Page: Added Loading Message and No Sections found when no courses (Not Logged In)","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/41"},{"author":{"id":"U_kgDOB3D2TQ","is_bot":false,"login":"just-in-fan","name":"Justin Fan"},"headRefName":"jf-BasicCourseSearchFeedback","number":38,"title":"Main Search Page: Added Loading Message and No Sections found when no courses","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/38"}]
