
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-courses-s26-02
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-02
pull_requests: [{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"auto-generate-course-schedule","number":54,"title":"Auto generate course schedule","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/54"},{"author":{"id":"U_kgDOBztTrQ","is_bot":false,"login":"Makkerel","name":"Kevin "},"headRefName":"Kevin-GEUXImprovement","number":51,"title":"Improved UX of GE Search","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/51"},{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"default-course-schedule","number":50,"title":"Default course schedule","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/50"},{"author":{"id":"U_kgDOCMR-Zg","is_bot":false,"login":"Andrew-UCSB","name":""},"headRefName":"Ab-EndQtr-from-currentQtr-UCSBAPIQuarterService-ScheduledJobs-IsStaleServiceTests","number":47,"title":"Made endQtrYYYQ pull from getCurrentEndQuarter rather than env variable for remaining backend files.","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/47"},{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"enrollment-history-page","number":45,"title":" added enrollmentHistory page + tests","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/45"}]
