title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s26/proj-courses-s26-02
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5NDc1MDQx","is_bot":false,"login":"Bombboox","name":"Arman Petrosyan"},"headRefName":"arman_user_pagination","number":25,"title":"Admin Users Pagination","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/25"},{"author":{"id":"U_kgDOCMR-Zg","is_bot":false,"login":"Andrew-UCSB","name":""},"headRefName":"Ab-EndQtr-from-currentQtr-CoursesStartup","number":22,"title":"EndQtr based off of CurrentQtr for CourseStartup","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/22"},{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"user-friendly-error-page","number":20,"title":"added friendly error page","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/20"},{"author":{"id":"U_kgDOBztTrQ","is_bot":false,"login":"Makkerel","name":"Kevin "},"headRefName":"Kevin-SummerSessionsColumn","number":19,"title":" Added Summer Session Column and tests for the updated column","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-02/pull/19"}]
